# Generated by Django 3.2.16 on 2023-06-22 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machinetrack', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('company_image', models.FileField(default='https://res.cloudinary.com/dz1h0duk6/image/upload/v1687467973/dr_box_buidea.png', upload_to='images/')),
                ('employees', models.CharField(max_length=300)),
                ('site_address', models.CharField(blank=True, max_length=250)),
                ('phone_number', models.PositiveIntegerField(blank=True)),
                ('field_a', models.CharField(max_length=30)),
                ('field_b', models.CharField(max_length=30)),
                ('field_c', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='machinetrack.profile')),
            ],
        ),
    ]
