# Generated by Django 3.2.16 on 2023-06-22 21:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinetrack', '0004_auto_20230622_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employees',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None), blank=True, size=10),
        ),
    ]
