# Generated by Django 3.2.16 on 2023-06-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinetrack', '0006_alter_company_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
