# Generated by Django 3.2.16 on 2023-06-28 21:43

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('machinetrack', '0007_company_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
