# Generated by Django 3.2.16 on 2023-06-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinetrack', '0008_alter_company_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=20, unique=True)),
                ('fusion_type', models.CharField(max_length=25)),
                ('voltage', models.PositiveIntegerField()),
                ('image', models.FileField(upload_to='images/')),
                ('manufacturer_product_code', models.CharField(max_length=20)),
            ],
        ),
    ]
