# Generated by Django 3.2.16 on 2023-06-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinetrack', '0009_machinemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinemodel',
            old_name='model',
            new_name='model_name',
        ),
    ]
