# Generated by Django 3.2.16 on 2023-06-29 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machinetrack', '0010_rename_model_machinemodel_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_reference', models.CharField(max_length=25, unique=True)),
                ('company_reference', models.CharField(blank=True, max_length=25)),
                ('serial_number', models.CharField(max_length=30, unique=True)),
                ('year_of_man', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
                ('is_electrical', models.BooleanField(default=True)),
                ('last_pat_test', models.DateTimeField()),
                ('last_calibration', models.DateTimeField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinetrack.machinemodel', to_field='model_name')),
            ],
        ),
    ]
