# Generated by Django 3.2.16 on 2023-07-03 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machinetrack', '0011_machineprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('machine_status', models.CharField(max_length=100)),
                ('changed_by', models.CharField(max_length=250)),
                ('changed_on', models.DateTimeField(auto_now=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='machinetrack.company', to_field='company_name')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinetrack.machineprofile', to_field='manufacturer_reference')),
            ],
        ),
    ]
