# Generated by Django 3.2.16 on 2023-07-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinetrack', '0012_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineprofile',
            name='last_calibration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='machineprofile',
            name='last_pat_test',
            field=models.DateField(),
        ),
    ]
