# Generated by Django 3.2.16 on 2023-07-03 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machinetrack', '0013_auto_20230703_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinetrack.company', to_field='company_name'),
        ),
    ]
