# Generated by Django 3.2.16 on 2023-07-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinetrack', '0016_alter_profile_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='machine_status',
        ),
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('none', 'none'), ('field_a', 'field_a'), ('field_b', 'field_b'), ('field_c', 'field_c')], default='none', max_length=100),
        ),
    ]
