# Generated by Django 3.2.16 on 2023-07-04 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinetrack', '0017_auto_20230704_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='end_date',
        ),
    ]
