# Generated by Django 3.2.16 on 2023-07-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinetrack', '0018_remove_job_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='po_reference',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
